title: Meu Blog
description: Long Form Jekyll theme built with SASS / COMPASS / SUSY

url: http://brianmaierjr.github.com/long-haul
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

markdown: kramdown
highlighter: rouge
plugins: [jekyll-paginate]
paginate: 5

navigation:
  - title: Inicio
    url: /index.html
  - title: Sobre
    url: /about
  - title: Contato
    url: /contact

social:
  github: alexandersantosh
  twitter: nenhum
  facebook: nenhum
  email: alexander.h.santos@gmail.com

google_analytics: "UA-58263416-1"
